# created by @jcoreio/toolchain-circle

version: 2.1

orbs:
  codecov: codecov/codecov@4.1.0

jobs:
  build:
    docker:
      - image: cimg/node:20.19.0

    steps:
      - checkout
      - run:
          name: Corepack enable
          command: sudo corepack enable
      - run:
          name: Install Dependencies
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            pnpm install --frozen-lockfile
      - run:
          name: set git username/pw
          command: |
            git config --global user.email "jedwards@fastmail.com "
            git config --global user.name "Andy Edwards"
      - run:
          name: Prepublish
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc prepublish
      - codecov/upload
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            [[ $(netstat -tnlp | grep -F 'circleci-agent') ]] || pnpm run tc release

workflows:
  build:
    jobs:
      - build:
          context:
            - github-release
