version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16

    steps:
      - checkout

      - run:
          name: Set up build
          command: |
            yarn config set registry "https://registry.npmjs.org/"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc
            if [[ -e .flowconfig ]]; then echo "server.max_workers=1" >> .flowconfig; fi

      - run:
          name: Install Dependencies
          command: |
            yarn install --frozen-lockfile
            cd packages/base-toolchain
            yarn install --frozen-lockfile

      - run:
          name: Build
          command: |
            cd packages/base-toolchain
            node makeVariants.js

      - run:
          name: Test
          command: |
            cd packages/base-toolchain
            yarn tc test
