version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.16

    steps:
      - checkout

      - run:
          name: Set up build
          command: |
            yarn config set registry "https://registry.npmjs.org/"
            echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
            echo "registry=https://registry.npmjs.org/" >> .npmrc

      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Build and Test
          command: ./make prepublish

      - run:
          name: Release js-toolchain
          command: cd packages/js-toolchain && yarn semantic-release
      - run:
          name: Release js-react-toolchain
          command: cd packages/js-react-toolchain && yarn semantic-release
      - run:
          name: Release ts-toolchain
          command: cd packages/ts-toolchain && yarn semantic-release
